bases/urls.py
from django.urls import path,include
from bases.views import Home

urlpatterns = [
    path("",Home.as_view(),name="home")
]

estudiante/urls.py
from django.urls import path,include
from .views import EstudianteView,EstudianteNew,EstudianteEdit,EstuanteDelete

urlpatterns = [
    path("estudiante/",EstudianteView.as_view(),name="estudiante-inicio"),
    path("estudiante/create",EstudianteNew.as_view(),name="estudiante-nuevo"),
    path("estudiante/<pk>/edit",EstudianteEdit.as_view(),name="estudiante-editar"),
    path("estudiante/<pk>/delete",EstuanteDelete.as_view(),name="estudiante-eliminar"),
]

sample/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include(('bases.urls','bases'),namespace='bases')),
    path('',include(('estudiante.urls','estudiante'),namespace="estudiante")),
    path('admin/', admin.site.urls),
]

bases/models.py
from django.db import models

# Create your models here.

estudiante/models.py
from django.db import models

# Create your models here.
class Estudiante(models.Model):
    id = models.BigAutoField(primary_key=True,verbose_name="ID")
    dni = models.CharField(max_length=8,help_text="DNI Estudiante")
    nombres = models.CharField(max_length=191,help_text="Nombres")
    apellidos= models.CharField(max_length=191,help_text="Apellidos")

    class Meta:
        verbose_name_plural ='estudiantes'
    
    def __str__(self) -> str:
        return '{0} {1}'.format(self.nombres,self.apellidos)

estudiante/forms.py
from django import forms
from django.forms import widgets
from .models import Estudiante

class EstudianteForm(forms.ModelForm):
    class Meta:
        model=Estudiante
        fields= ['dni','nombres','apellidos']
        labels={
            'dni': 'D.N.I.:','nombres':'Nombres',
            'apellidos': 'Apellidos'
        }
        widgets = {
            'dni':forms.TextInput,
            'nombres':forms.TextInput,
            'apellidos':forms.TextInput
        }

        def __init__(self,*args, **kwargs) -> None:
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'input'
                })
            pass

bases/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.

class Home (generic.TemplateView):
    template_name="bases/home.html"

estudiante/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Estudiante
from .forms import EstudianteForm

# Create your views here.
class EstudianteView(generic.ListView):
    paginate_by=5
    model = Estudiante
    context_object_name = 'estudiantes'
    template_name="estudiante/inicio.html"

class EstudianteNew(generic.CreateView):
    model= Estudiante
    template_name="estudiante/create.html"
    form_class=EstudianteForm
    success_url = reverse_lazy('estudiante:estudiante-inicio')

class EstudianteEdit(generic.UpdateView):
    model=Estudiante
    fields=['dni','nombres','apellidos']
    template_name="estudiante/edit.html"
    success_url = reverse_lazy('estudiante:estudiante-inicio')

class EstuanteDelete(generic.DeleteView):
    model=Estudiante
    success_url = reverse_lazy('estudiante:estudiante-inicio')

bases/templates/bases/home.html
{% extends 'sample/base.html' %}


{% block contenido %}
<section class="hero is-warning is-medium">
    <div class="hero-body">
      <p class="title">
        Home
      </p>
      <p class="subtitle">
         Bienvenido(a) al Sistema
      </p>
    </div>
  </section>
{% endblock contenido %}

estudiante/templates/estudiante/create.html
{% extends 'sample/base.html' %}


{% block contenido %}
<section class="hero is-warning is-small">
    <div class="hero-body">
      <p class="title">
        Nuevo Estudiante
      </p>
      <p class="subtitle">
       
      </p>
    </div>
</section>
 <div class="container">
    <div class="columns">
        <div class="column">
            <form method="POST"  class="from-inline" id="form-sucursal" >
                {% csrf_token %}
                <div class="columns">
                    <div class="column is-two-fifths">
                        <div class="field">
                            <label class="label">D.N.I</label>
                            <div class="control">
                                <input class="input" type="text" placeholder="Ingrese D.N.I." 
                                    id="id_dni" name="dni" maxlength="8">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column is-two-fifths">
                        <div class="field">
                            <label class="label">Nombres</label>
                            <div class="control">
                                <input class="input" type="text" placeholder="Ingrese Nombres." 
                                    id="id_nombres" name="nombres">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column is-two-fifths">
                        <div class="field">
                            <label class="label">Apellidos</label>
                            <div class="control">
                                <input class="input" type="text" placeholder="Ingrese Apellidos" 
                                    id="id_apellidos" name="apellidos">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="colums">
                    <div class="column is-two-fifths">
                        <a href="{% url 'estudiante:estudiante-inicio' %}" class="button is-danger">
                        Cancelar
                        </a>
                        <button class="button is-success" type="submit">Guardar</button>
                    </div>
                </div>
            </form>
            {% comment %} {{ form.as_p }} {% endcomment %}
        </div>
    </div>
  </div>
{% endblock contenido %}

estudiante/templates/estudiante/edit.html
{% extends 'sample/base.html' %}


{% block contenido %}
<section class="hero is-warning is-small">
    <div class="hero-body">
      <p class="title">
        Nuevo Estudiante
      </p>
      <p class="subtitle">
       
      </p>
    </div>
</section>
 <div class="container">
    <div class="columns">
        <div class="column">
            <form method="POST"  class="from-inline" id="form-sucursal" >
                {% csrf_token %}
                <div class="columns">
                    <div class="column is-two-fifths">
                        <div class="field">
                            <label class="label">D.N.I</label>
                            <div class="control">
                                <input class="input" type="text" placeholder="Ingrese D.N.I." 
                                    id="id_dni" name="dni" maxlength="8" 
                                    value="{{ estudiante.dni }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column is-two-fifths">
                        <div class="field">
                            <label class="label">Nombres</label>
                            <div class="control">
                                <input class="input" type="text" placeholder="Ingrese Nombres." 
                                    id="id_nombres" name="nombres"
                                    value="{{ estudiante.nombres }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column is-two-fifths">
                        <div class="field">
                            <label class="label">Apellidos</label>
                            <div class="control">
                                <input class="input" type="text" placeholder="Ingrese Apellidos" 
                                    id="id_apellidos" name="apellidos"
                                    value="{{ estudiante.apellidos }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="colums">
                    <div class="column is-two-fifths">
                        <a href="{% url 'estudiante:estudiante-inicio' %}" class="button is-danger">
                        Cancelar
                        </a>
                        <button class="button is-success" type="submit">Guardar</button>
                    </div>
                </div>
            </form>
            {% comment %} {{ form.as_p }} {% endcomment %}
        </div>
    </div>
  </div>
{% endblock contenido %}

estudiante/templates/estudiante/estudiante_confirm_delete.html
{% extends 'sample/base.html' %}


{% block contenido %}
<section class="hero is-warning is-small">
    <div class="hero-body">
      <p class="title">
        Nuevo Estudiante
      </p>
      <p class="subtitle">
       
      </p>
    </div>
</section>
 <div class="container">
    <div class="columns">
        <div class="column">
            <form method="post">{% csrf_token %}
                ¿Estás seguro que deseas borrar el Estudiante "{{ estudiante }}"?
                <br>
                <a href="{% url 'estudiante:estudiante-inicio' %}" class="button is-danger">
                    No
                </a>
                <input type="submit" value="Si" class="button is-success" />
            </form>            
        </div>
    </div>
  </div>
{% endblock contenido %}

estudiante/templates/estudiante/inicio.html
{% extends 'sample/base.html' %}


{% block contenido %}
<section class="hero is-warning is-small">
    <div class="hero-body">
      <p class="title">
        Estudiante
      </p>
      <p class="subtitle">
        Listado de Estudiantes
      </p>
    </div>
</section>
 <div class="container">
    <div class="columns">
      <div class="column">
        <a href="{% url 'estudiante:estudiante-nuevo' %}" class="button is-link">
          Nuevo Estudiante
        </a>
        <table class="table is-fullwidth is-bordered">
          <thead class="">
            <tr>
              <th>DNI</th>
              <th>Nombres</th>
              <th>Apellidos</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% if not estudiantes %}
                <tr>
                    <td colspan="4" class="has-text-danger has-text-centered">
                        --Datos No Registrados--
                    </td>
                </tr>
            {% else %}
                {% for item in estudiantes %}
                <tr>
                    <td>{{ item.dni }}</td>
                    <td>{{ item.nombres }}</td>
                    <td>{{ item.apellidos }}</td>
                    <td>
                        <a href="{% url 'estudiante:estudiante-editar' item.id %}" class="button is-warning is-small">
                            Editar
                        </a>
                        <a href="{% url 'estudiante:estudiante-eliminar' item.id %}" class="button is-danger is-small">
                            Eliminar
                        </a>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}

          </tbody>
        </table>
        <div class="pagination is-rounded" role="navigation" aria-label="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1"class="pagination-link">&laquo; Primero</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="pagination-previous">Anterior</a>
                {% endif %}

                <span class="current">
                    P&aacute;gina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="pagination-next">Siguiente</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="pagination-link">&Uacute;ltimo &raquo;</a>
                {% endif %}
            </span>
        </div>
      </div>
    </div>
  </div>
{% endblock contenido %}

templates/sample/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Estuadiantes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Inicio
          </a>

          <a class="navbar-item" href="{% url 'estudiante:estudiante-inicio' %}">
            Estudiante
          </a>
        </div>
      </div>
    </nav>
     {% csrf_token %}
     {% block contenido %}
     {% endblock contenido %}
    <footer class="footer">
    </footer>
  </body>
</html>